# Generated by Django 3.2.1 on 2022-05-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category_photo',
            new_name='image_category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='where_photo',
            new_name='location_taken',
        ),
    ]
