# Generated by Django 3.2.1 on 2022-05-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0002_auto_20220529_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
