# Generated by Django 3.2.1 on 2022-05-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='artphotos/'),
        ),
    ]
