# Generated by Django 3.2.1 on 2022-05-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0006_rename_image_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
