# Generated by Django 3.2 on 2022-06-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0007_rename_image_url_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='where_photo',
            name='city',
        ),
    ]
